name: Deploy WordPress plugin
on:
  release:
    types: [published]
    
jobs:
  build:
    name: Deploy WordPress plugin
    runs-on: ubuntu-20.04
    steps:
      # 3. Checkout before Use this deployment action
      - name: Checkout
        uses: actions/checkout@v3
      # 4. Use action with environment variable set by secrets
      - name: Deploy
        uses: yukihiko-shinoda/action-deploy-wordpress-plugin@v2
        env:
          SVN_REPOSITORY_URL: ${{ secrets.SVN_URL }}
          SVN_USER_NAME: ${{ secrets.SVN_USERNAME }}
          SVN_USER_PASSWORD: ${{ secrets.SVN_PASSWORD }}
