name: Sync to SVN on Release

on:
  release:
    types: [published]

jobs:
  sync-to-svn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SVN
        run: sudo apt-get install subversion

      - name: Sync repository to SVN
        env:
          SVN_URL: ${{ secrets.SVN_URL }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          svn checkout --username $SVN_USERNAME --password $SVN_PASSWORD $SVN_URL svn-repo
          rsync -av --exclude='.git' --delete ./ svn-repo/
          cd svn-repo
          svn add --force .
          svn commit -m "Sync GitHub release to SVN" --username $SVN_USERNAME --password $SVN_PASSWORD

      - name: Tag SVN with release tag
        env:
          SVN_URL: ${{ secrets.SVN_URL }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          svn copy --username $SVN_USERNAME --password $SVN_PASSWORD $SVN_URL/trunk $SVN_URL/tags/$RELEASE_TAG -m "Tagging release $RELEASE_TAG"
